<?php

use PHPUnit\Framework\TestCase;
use zukr\test2\Foo;

/**
 * Project: 2
 * Date: 05.07.2019
 * Time: 22:15
 */
class TestFoo extends TestCase
{

    private $b;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->b = new Foo();
    }

    public function testBar(): void
    {

        $this->assertSame(4, $this->b->bar(), 'ok1');
    }

    public function testNotSame(): void
    {
        $this->assertNotSame(5, $this->b->bar(), 'ok2');
    }
}